###################  Microservice base configuration  ###################
spring:
  application:
    name: dux-manager
    version: 0.0.1-SNAPSHOT
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

server:
  port: 8443
  servlet.context-path: /${spring.application.name}
  ssl:
    enabled: true # enable https
    key-store: classpath:certificate/dux-manager.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: dux-manager

logging.level:
  root: INFO
  org.springframework: INFO
  com.portfolio: INFO

###################  MongoDB configuration  ###################
spring.data.mongodb:
  uri: mongodb://localhost:27017/DuxManager
  auto-index-creation: true
