###################  Microservice base configuration  ###################
spring:
  application:
    name: dux-manager
    version: 0.0.1-SNAPSHOT
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

server:
  port: ${SERVER_PORT}
  servlet.context-path: /${spring.application.name}
  ssl:
    enabled: true # enable https
    key-store: ${KEY_STORE}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${KEY_ALIAS}

logging.level:
  root: INFO
  org.springframework: INFO
  com.portfolio: INFO

###################  MongoDB configuration  ###################
spring.data.mongodb:
  uri: ${MONGO_URI}
  auto-index-creation: true
