###################  Microservice base configuration  ###################
spring:
  application:
    name: dux-manager
    version: 0.0.1-SNAPSHOT
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:10000/.well-known/jwks.json

# default port for HTTP:   80
# default port for HTTPS: 443
server:
  port: 8080
  servlet.context-path: /${spring.application.name}

logging.level:
  root: INFO
  org.springframework: INFO
  com.portfolio: INFO

###################  MongoDB configuration  ###################
spring.data.mongodb:
  uri: mongodb://localhost:27017/DuxManager
  auto-index-creation: true
